version: 0.6.0-ci{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.6.0"
  assembly_file_version: "0.6.0"
  assembly_informational_version: "0.6.0-ci{build}"

build:
  project: src/Gemini.sln
  publish_nuget: true